# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

fastlane_require 'dotenv'


before_all do |lane|
  # load only locally
  # in CI we use the environment variables
  if ENV["CI"].nil?
    Dotenv.overload '../.env'
  end
end

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      workspace: "ios/StockMarketApp.xcworkspace",
      scheme: "StockMarketApp"
    )
  end

  desc "Publish a new iOS version to TestFlight"
  lane :release_test_flight do
    if ENV["CI"]
      setup_ci
      app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
      )
    else
      app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_filepath: "./secrets/App Store Connect Auth Key.p8",
      )
    end

    match(type: "appstore")

    version = get_version_number(
      xcodeproj: "ios/StockMarketApp.xcodeproj",
    )

    latest_release = latest_testflight_build_number(version: version)

    increment_build_number({
      xcodeproj: "ios/StockMarketApp.xcodeproj",
      build_number: latest_release + 1
    })
    
    build_app(workspace: "ios/StockMarketApp.xcworkspace", scheme: "StockMarketApp")

    upload_to_testflight
  end
end

platform :android do
  desc "Build Android app"
  lane :build do
    gradle(
      task: "clean assembleRelease",
      project_dir: "android/"
    )
  end
end
