# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      workspace: "ios/StockMarketApp.xcworkspace",
      scheme: "StockMarketApp"
    )
  end

  desc "Run iOS tests"
  lane :test do
    run_tests(
      workspace: "ios/StockMarketApp.xcworkspace",
      scheme: "StockMarketApp"
    )
  end
end

platform :android do
  desc "Build Android app"
  lane :build do
    gradle(
      task: "clean assembleRelease",
      project_dir: "android/"
    )
  end
end
