# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

fastlane_require 'dotenv'


before_all do |lane|
  # load only locally
  # in CI we use the environment variables
  if ENV["CI"].nil?
    Dotenv.overload '../.env'
  end
end

private_lane :setup_store_connect do
  if ENV["CI"]
    setup_ci
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )
  else
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "./secrets/App Store Connect Auth Key.p8",
    )
  end
end

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      workspace: "ios/StockMarketApp.xcworkspace",
      scheme: "StockMarketApp"
    )
  end

  desc "Publish a new iOS version to TestFlight"
  lane :release_test_flight do
    setup_store_connect

    match(type: "appstore")

    version = get_version_number(
      xcodeproj: "ios/StockMarketApp.xcodeproj",
    )

    latest_release = latest_testflight_build_number(version: version)

    increment_build_number({
      xcodeproj: "ios/StockMarketApp.xcodeproj",
      build_number: latest_release + 1
    })
    
    build_app(workspace: "ios/StockMarketApp.xcworkspace", scheme: "StockMarketApp")

    upload_to_testflight
  end
end

platform :android do
  desc "Build Android app"
  lane :build do
    gradle(
      task: "clean assembleRelease",
      project_dir: "android/"
    )
  end
end


# lane with option version
desc "Update versions"
lane :update_versions do |options|
  setup_store_connect

  the_version = options[:version]

  # update build number for ios
  latest_release = latest_testflight_build_number(version: the_version)

  puts "latest_release: #{latest_release}"
  
  increment_build_number({
    xcodeproj: "ios/StockMarketApp.xcodeproj",
    build_number: latest_release + 1
  })
  

  # update version code for android
  latest_android_version_code = android_get_version_code({
    gradle_file: "android/app/build.gradle",
  })

  puts "latest_android_version_code: #{latest_android_version_code}"

  android_set_version_code({
    gradle_file: "android/app/build.gradle",
    version_code: latest_android_version_code.to_i + 1
  })

  # update version name for ios
  increment_version_number({
    xcodeproj: "ios/StockMarketApp.xcodeproj",
    version_number: the_version
  })
  
  # update version name for android
  android_set_version_name({
    gradle_file: "android/app/build.gradle",
    version_name: the_version
  })

end
